# Generated by Django 5.1 on 2025-02-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phonenumber',
            field=models.CharField(max_length=30),
        ),
    ]
